require:
  - rubocop-rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3
  Exclude:
    - "bin/**/*"
    - "db/schema.rb"
    - "node_modules/**/*"
    - "tmp/**/*"
    - "vendor/**/*"

Rails:
  Enabled: true

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Enable: false
